### ISSUE TITLE
Coursera Code of Honor

### ISSUE THREAD

**Issue by tOverney** [aywengo/CourseraRxProgramming#1]
Dear @aywengo !
Posting solutions is against the coursera code of honor.
Please remove that repo or make it private!

Tristan,
staff for the reactive programming mooc.

**Comment by aywengo** [comment]
Oh. Ok. I'll remove the repo.

**Comment by tOverney** [comment]
thanks

**Comment by aywengo** [comment]
I made the repopsitory private. And I won't share with anybody. I can add you as the watcher - to be sure I won't add anybody else.  
I'm coding on several PCs. So for me it's nice to have repo.
